### ISSUE TITLE
Listen Interval

### ISSUE THREAD

**Issue by Tockra** [brutella/can#12]
Hey Guys,

in what interval does this library gets can bus signals? 
Could my program pass some signals? Does it block while now signal comes? 
What is with CPU usage while listening?

T

**Comment by brutella** [comment]
> in what interval does this library gets can bus signals?

The library reads as fast as it can from the socket.

> Could my program pass some signals?

I think this depends on the network driver you are using.
I haven't experienced that with socketCAN.
