### ISSUE TITLE
add time stamp to received frames

### ISSUE THREAD

**Issue by skladd** [brutella/can#3]
Hi there,

I would love to get time stamps of received CAN frames as accurate as possible. At least for Linux it should be possible.

From Linux SocketCAN documentation:

> An accurate timestamp can be obtained with an ioctl(2) call after reading  a message from the socket:

    struct timeval tv;
    ioctl(s, SIOCGSTAMP, &tv);

PR follows.

Regards, Stephan

**Comment by skladd** [comment]
@brutella Matthias, are you going to maintain your repositories "can" and "canopen"? Otherwise, I would just switch to my forks... Regards, Stephan

**Comment by brutella** [comment]
Yes, I will take a look at your changes in the next couple of days.
